version: "3"
services:
  redis:
    image: "redis:7-alpine"
    expose:
      - "6379"
  postgres:
    image: "postgres:14-alpine"
    env_file: /app/cloud/.env
    expose:
      - "5432"
    volumes:
      - /app/cloud/postgres_data:/var/lib/postgresql/data
  cloud-backend:
    image: "mderam/cloud-backend:latest"
    restart: always
    env_file: /app/cloud/.env
    environment:
      - NODE_ENV=production
      - DRIVE_PATH=/var/lib/cloud/data
      - PORT=8000
    depends_on:
      - redis
      - postgres
    expose:
      - "8000"
    ports:
      - "6379:6379"
      - "5432:5432"
    volumes:
      - /app/cloud/drive_data:/var/lib/cloud/data
  cloud-frontend:
    image: "mderam/cloud-frontend:latest"
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
  cloud-nginx:
    image: "mderam/cloud-nginx:latest"
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "8000:8000"
    volumes:
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - cloud-backend
      - cloud-frontend

volumes:
  nginx_secrets:
